import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync
} from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'node-html-parser'
import { describe, expect, it } from 'vitest'
import { pages, routeFile, toolNames } from './site-contract.js'

const siteRoot = fileURLToPath(new URL('../', import.meta.url))
const distDir = join(siteRoot, 'dist')
const contentDir = join(siteRoot, 'src', 'content', 'docs')
const origin = 'https://memscope.esrc.dev'

function read(relativePath: string): string {
  return readFileSync(join(distDir, relativePath), 'utf8')
}

function filesUnder(root: string): string[] {
  return readdirSync(root, { withFileTypes: true }).flatMap((entry) => {
    const path = join(root, entry.name)
    return entry.isDirectory() ? filesUnder(path) : [path]
  })
}

function sourceFile(route: string): string {
  if (route === '/') return 'index.md'
  if (route === '/reference/mcp-tools/') return 'reference/mcp-tools/index.md'
  return `${route.slice(1, -1)}.md`
}

const html = new Map(
  pages.map((page) => [page.route, read(routeFile(page.route))] as const)
)
const dom = new Map(
  [...html].map(([route, value]) => [route, parse(value)] as const)
)

const generatedFileComment =
  '# Generated by mcp-site-platform-cloudflare-pages. Do not edit; configure via the cloudflarePages() integration.'

const expectedHeaders = [
  generatedFileComment,
  '',
  '/*',
  '  X-Content-Type-Options: nosniff',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '',
  '/_astro/*',
  '  Cache-Control: public, max-age=31556952, immutable',
  ''
].join('\n')

const expectedToolNames = [...toolNames]
const historicalToolAnchors = [
  'configuration',
  'tool-list',
  'read-first-examples',
  'scan-boundary',
  'result-shape',
  'lua-and-scripts'
]

describe('ordinary Starlight source and dependency boundary', () => {
  it('keeps exactly one ordinary Markdown source for every canonical route', () => {
    const markdown = filesUnder(contentDir)
      .filter((path) => path.endsWith('.md'))
      .map((path) => relative(contentDir, path).replaceAll('\\', '/'))
      .sort()
    const expected = pages.map((page) => sourceFile(page.route)).sort()

    expect(markdown).toEqual(expected)
    for (const page of pages) {
      const source = readFileSync(join(contentDir, sourceFile(page.route)), 'utf8')
      expect(source.startsWith('---\n')).toBe(true)
      expect(source).toContain(`title: ${JSON.stringify(page.title)}`)
      expect(source).toContain(`description: ${JSON.stringify(page.description)}`)
    }

    const preamble = join(siteRoot, 'tool-reference-preamble.md')
    expect(existsSync(preamble)).toBe(true)
    expect(preamble.startsWith(contentDir)).toBe(false)
    expect(markdown).not.toContain('tool-reference-preamble.md')
  })

  it('declares only honest version dependencies and no machine locator or fabricated lock', () => {
    const packageJson = JSON.parse(readFileSync(join(siteRoot, 'package.json'), 'utf8')) as {
      dependencies: Record<string, string>
      scripts: Record<string, string>
    }

    expect(packageJson.dependencies).toEqual({
      '@astrojs/starlight': '0.41.7',
      astro: '7.2.4',
      'mcp-site-platform': '0.2.0'
    })
    expect(existsSync(join(siteRoot, 'package-lock.json'))).toBe(true)
    expect(JSON.stringify(packageJson)).not.toMatch(/(?:file:|link:|git\+|github:|\.\.\/|[A-Za-z]:[\\/])/)
    expect(Object.values(packageJson.scripts).join('\n')).not.toMatch(/\b(?:python|pip|memscope-mcp)\b/i)
  })

  it('contains no product-runtime import path or obsolete proof machinery', () => {
    const authoredCode = [
      join(siteRoot, 'astro.config.mjs'),
      ...filesUnder(join(siteRoot, 'src')).filter((path) => /\.(?:js|mjs|ts)$/.test(path))
    ]
    for (const path of authoredCode) {
      const code = readFileSync(path, 'utf8')
      expect(code, path).not.toMatch(/memscope_mcp|runtime_snapshot|child_process|from\s+['"]mcp['"]/)
    }
    expect(filesUnder(siteRoot).filter((path) => path.endsWith('.py'))).toEqual([])
    for (const obsolete of [
      'build.py',
      'component-pin.json',
      'crawler-policy-v1.json',
      'http-probes-v1.json',
      'privacy-policy-v1.json',
      'product-manifest-v1.json',
      'retrieval-queries-v1.json',
      'runtime_snapshot.py',
      'schemas'
    ]) {
      expect(existsSync(join(siteRoot, obsolete)), obsolete).toBe(false)
    }
  })
})

describe('canonical route and navigation output', () => {
  it('builds exactly the 34 directory routes plus the official 404 page', () => {
    const builtHtml = filesUnder(distDir)
      .filter((path) => path.endsWith('.html'))
      .map((path) => relative(distDir, path).replaceAll('\\', '/'))
      .sort()
    const expected = [...pages.map((page) => routeFile(page.route)), '404.html'].sort()

    expect(pages).toHaveLength(34)
    expect(builtHtml).toEqual(expected)
  })

  it('preserves route order in the rendered Starlight sidebar', () => {
    const representative = dom.get('/get-started/install/')!
    const canonical = new Set(pages.map((page) => page.route))
    const sidebarRoutes = representative
      .querySelectorAll('#starlight__sidebar a[href]')
      .map((anchor) => anchor.getAttribute('href') ?? '')
      .filter((href) => canonical.has(href))

    expect(sidebarRoutes).toEqual(pages.map((page) => page.route))
  })

  it.each(pages)('renders the title, summary, canonical URL, and local favicon for $route', (page) => {
    const document = dom.get(page.route)!

    expect(document.querySelector('title')?.text).toBe(`${page.title} | Memscope`)
    expect(document.querySelector('meta[name="description"]')?.getAttribute('content')).toBe(
      page.description
    )
    expect(document.querySelector('link[rel="canonical"]')?.getAttribute('href')).toBe(
      origin + page.route
    )
    expect(document.querySelector('meta[property="og:title"]')?.getAttribute('content')).toBe(
      page.title
    )
    expect(document.querySelector('meta[property="og:description"]')?.getAttribute('content')).toBe(
      page.description
    )
    expect(document.querySelector('link[rel*="icon"]')?.getAttribute('href')).toBe('/favicon.svg')
  })

  it('resolves every internal link and fragment across all canonical pages and 404', () => {
    const documents = new Map(dom)
    documents.set('/404/', parse(read('404.html')))
    const unresolved: string[] = []

    for (const [sourceRoute, document] of documents) {
      for (const anchor of document.querySelectorAll('a[href]')) {
        const href = anchor.getAttribute('href') ?? ''
        if (/^(?:mailto:|tel:)/i.test(href)) continue
        let target: URL
        try {
          target = new URL(href, origin + sourceRoute)
        } catch {
          unresolved.push(`${sourceRoute}: invalid URL ${JSON.stringify(href)}`)
          continue
        }
        if (target.origin !== origin) continue
        const targetRoute = target.pathname
        const targetDocument = documents.get(targetRoute)
        if (targetDocument === undefined) {
          unresolved.push(`${sourceRoute}: ${href} -> missing canonical route ${targetRoute}`)
          continue
        }
        if (!target.hash) continue
        const id = decodeURIComponent(target.hash.slice(1))
        if (!targetDocument.querySelectorAll('[id]').some((element) => element.getAttribute('id') === id)) {
          unresolved.push(`${sourceRoute}: ${href} -> missing id=${JSON.stringify(id)}`)
        }
      }
    }

    expect(unresolved, unresolved.join('\n')).toEqual([])
  })
})

describe('Cloudflare Pages and discovery files', () => {
  it('emits exactly 33 derived no-slash redirects to canonical directory routes', () => {
    const lines = read('_redirects').split(/\r?\n/)
    expect(lines[0]).toBe(generatedFileComment)
    const rules = lines.slice(1).filter(Boolean)
    const expected = pages
      .filter((page) => page.route !== '/')
      .map((page) => `${page.route.slice(0, -1)} ${page.route} 301`)
      .sort()

    expect(rules).toHaveLength(33)
    expect([...rules].sort()).toEqual(expected)
  })

  it('emits only conventional static response headers', () => {
    expect(read('_headers')).toBe(expectedHeaders)
    expect(read('_headers')).not.toMatch(/Content-Security-Policy/i)
  })

  it('uses official sitemap output for exactly the canonical routes', () => {
    expect(read('sitemap-index.xml')).toContain(
      '<loc>https://memscope.esrc.dev/sitemap-0.xml</loc>'
    )
    const locations = [...read('sitemap-0.xml').matchAll(/<loc>([^<]+)<\/loc>/g)].map(
      (match) => match[1]
    )
    expect(locations.sort()).toEqual(pages.map((page) => origin + page.route).sort())
  })

  it('copies bounded robots, llms, and favicon files without evidence artifacts', () => {
    for (const name of ['robots.txt', 'llms.txt', 'favicon.svg']) {
      expect(read(name)).toBe(readFileSync(join(siteRoot, 'public', name), 'utf8'))
    }
    expect(read('robots.txt')).toContain('Sitemap: https://memscope.esrc.dev/sitemap-index.xml')
    expect(Buffer.byteLength(read('robots.txt'))).toBeLessThanOrEqual(256)
    expect(read('llms.txt')).toContain('Windows process-memory MCP documentation')
    expect(read('llms.txt')).toContain('makes no deployment, availability, hosting API')
    expect(Buffer.byteLength(read('llms.txt'))).toBeLessThanOrEqual(2048)
    expect(filesUnder(join(siteRoot, 'public')).map((path) => relative(join(siteRoot, 'public'), path)).sort()).toEqual([
      'favicon.svg',
      'llms.txt',
      'robots.txt'
    ])
  })
})

describe('tool reference, content behavior, and search output', () => {
  it('keeps the exact ordered 11-tool product snapshot and generated headings', () => {
    const tools = JSON.parse(readFileSync(join(siteRoot, 'tools.json'), 'utf8')) as {
      formatVersion: number
      server: { name: string; displayName: string }
      tools: Array<{ name: string; description: string; inputSchema: unknown; outputSchema?: unknown }>
    }
    expect(tools.formatVersion).toBe(1)
    expect(tools.server).toEqual({ name: 'memscope-mcp', displayName: 'Memscope MCP' })
    expect(tools.tools.map((tool) => tool.name)).toEqual(expectedToolNames)
    for (const tool of tools.tools) {
      expect(tool.description.length).toBeGreaterThan(0)
      expect(tool.description.length).toBeLessThanOrEqual(2000)
      expect(tool.inputSchema).toMatchObject({ type: 'object' })
      expect(Buffer.byteLength(JSON.stringify(tool.inputSchema, null, 2))).toBeLessThanOrEqual(65_536)
      if (tool.outputSchema !== undefined) {
        expect(Buffer.byteLength(JSON.stringify(tool.outputSchema, null, 2))).toBeLessThanOrEqual(65_536)
      }
    }

    const toolDocument = dom.get('/reference/mcp-tools/')!
    const headings = toolDocument.querySelectorAll('main h2').map((heading) => ({
      id: heading.getAttribute('id'),
      text: heading.text.trim()
    }))
    expect(headings.slice(0, historicalToolAnchors.length)).toEqual([
      { id: 'configuration', text: 'Configuration' },
      { id: 'tool-list', text: 'Tool list' },
      { id: 'read-first-examples', text: 'Read-first examples' },
      { id: 'scan-boundary', text: 'Scan boundary' },
      { id: 'result-shape', text: 'Result shape' },
      { id: 'lua-and-scripts', text: 'Lua and scripts' }
    ])
    expect(headings.slice(historicalToolAnchors.length)).toEqual(
      expectedToolNames.map((name) => ({ id: name, text: name }))
    )
    expect(toolDocument.querySelector('main')?.text).toContain('Server: Memscope MCP')

    const multilineNames = new Set([
      'processes', 'attach', 'modules', 'read', 'write', 'dump', 'chain', 'lua', 'scripts'
    ])
    expect(tools.tools.filter((tool) => tool.description.includes('\n')).map((tool) => tool.name)).toEqual(
      expectedToolNames.filter((name) => multilineNames.has(name))
    )
    const paragraphs = toolDocument.querySelectorAll('main p')
    for (const tool of tools.tools) {
      const normalized = tool.description.trim().replace(/[ \n]+/g, ' ')
      const paragraph = paragraphs.find((candidate) => candidate.text.trim() === normalized)
      expect(paragraph, tool.name).toBeDefined()
      expect(paragraph?.querySelector('a, code, img, script, style'), tool.name).toBeNull()
    }
  })

  it('restores historical guidance anchors on the generated schema route', () => {
    const toolDocument = dom.get('/reference/mcp-tools/')!
    for (const anchor of historicalToolAnchors) {
      expect(toolDocument.querySelector(`main #${anchor}`), anchor).not.toBeNull()
    }
    expect(toolDocument.querySelectorAll('main table')).not.toHaveLength(0)
    expect(toolDocument.querySelector('main')?.text).toContain(
      'The server does not add a separate MCP tool for plugins.'
    )
    expect(toolDocument.querySelector('main')?.text).toContain(
      'The full function contract is in the Lua reference.'
    )
  })

  it('keeps difficult tool descriptions visible and structurally inert', () => {
    const toolDocument = dom.get('/reference/mcp-tools/')!
    const descriptions = toolDocument.querySelectorAll('main p')
    const chain = descriptions.find((paragraph) =>
      paragraph.text.includes('[[base+off0]+off1]... Offsets accept hex: ["0x148", "0x10"].')
    )
    const scripts = descriptions.find((paragraph) =>
      paragraph.text.includes('Scripts live under $MEMSCOPE_HOME/scripts/<process>/<name>.lua.')
    )

    expect(chain).toBeDefined()
    expect(scripts).toBeDefined()
    for (const paragraph of [chain!, scripts!]) {
      expect(paragraph.querySelector('a, code, img, script, style')).toBeNull()
    }
  })

  it('preserves rich code, table, and anchor content in ordinary pages', () => {
    const candidates = [...dom.entries()].flatMap(([route, document]) =>
      document.querySelectorAll('main pre, main table').map((element) => ({ route, element }))
    )
    expect(candidates.filter(({ element }) => element.tagName === 'PRE').length).toBeGreaterThan(40)
    expect(candidates.filter(({ element }) => element.tagName === 'TABLE').length).toBeGreaterThanOrEqual(5)
    for (const { route, element } of candidates) {
      expect(element.getAttribute('tabindex'), `${route}: ${element.tagName}`).toBe('0')
    }

    expect(dom.get('/plugins/lifecycle-and-contract/')?.querySelector('#composition')).not.toBeNull()
    expect(dom.get('/plugins/lifecycle-and-contract/')?.querySelector('#attach-and-detach')).not.toBeNull()
    expect(dom.get('/reference/lua/')?.querySelector('#code-execution')).not.toBeNull()
    expect(dom.get('/reference/scanning/')?.querySelector('#mcp-scan')).not.toBeNull()
  })

  it('generates nonempty official Pagefind data for the complete content set', () => {
    const pagefindDir = join(distDir, 'pagefind')
    const entry = JSON.parse(readFileSync(join(pagefindDir, 'pagefind-entry.json'), 'utf8')) as {
      languages: Record<string, { page_count: number; wasm: string }>
    }
    expect(entry.languages.en?.page_count).toBeGreaterThanOrEqual(34)
    expect(statSync(join(pagefindDir, 'pagefind.js')).size).toBeGreaterThan(1024)
    expect(filesUnder(pagefindDir).reduce((total, path) => total + statSync(path).size, 0)).toBeGreaterThan(
      20 * 1024
    )
  })
})

describe('removed editorial framing', () => {
  const rejectedPhrases = [
    'Use with caution',
    'as untrusted',
    'Before enabling powerful operations',
    'safe first session',
    'Safe first session',
    'authorized live-process'
  ]
  const rejectedHeadings = [
    'Safety checklist',
    'Safety',
    'Trust and data',
    'Trust and state',
    'Plugin trust',
    'Data trust',
    'Operational practice'
  ]

  function builtText(): string[] {
    return filesUnder(distDir)
      .filter((path) => path.endsWith('.html') || path === join(distDir, 'llms.txt'))
      .map((path) => readFileSync(path, 'utf8'))
  }

  it('keeps user-rejected warning phrases out of every built page and llms.txt', () => {
    const hits: string[] = []
    for (const text of builtText()) {
      for (const phrase of rejectedPhrases) {
        if (text.includes(phrase)) hits.push(phrase)
      }
    }
    expect(hits, [...new Set(hits)].join(', ')).toEqual([])
  })

  it('keeps generic Safety/Trust headings out of every built page', () => {
    const offenders: string[] = []
    for (const [route, document] of dom) {
      for (const heading of document.querySelectorAll('main h1, main h2, main h3')) {
        if (rejectedHeadings.includes(heading.text.trim())) offenders.push(`${route}: ${heading.text.trim()}`)
      }
    }
    expect(offenders).toEqual([])
  })

  it('keeps the site description free of authorization framing in config and metadata output', () => {
    const config = readFileSync(join(siteRoot, 'astro.config.mjs'), 'utf8')
    expect(config).not.toContain('authorized live-process research')
    const tools = JSON.parse(readFileSync(join(siteRoot, 'tools.json'), 'utf8')) as {
      tools: Array<{ name: string; description: string }>
    }
    for (const tool of tools.tools) {
      expect(tool.description.includes('Use with caution'), tool.name).toBe(false)
    }
  })
})

describe('self-contained runtime assets', () => {
  it('references no remote runtime asset from any HTML page', () => {
    const violations: string[] = []
    for (const [route, document] of dom) {
      const references = [
        ...document.querySelectorAll(
          'script[src], img[src], source[src], iframe[src], video[src], audio[src], embed[src], object[data], video[poster]'
        ).map((element) => element.getAttribute('src') ?? element.getAttribute('data') ?? ''),
        ...document.querySelectorAll('link[href]').filter((element) =>
          /stylesheet|icon|preload|prefetch|manifest|sitemap/.test(element.getAttribute('rel') ?? '')
        ).map((element) => element.getAttribute('href') ?? ''),
        ...document.querySelectorAll('[srcset]').flatMap((element) =>
          (element.getAttribute('srcset') ?? '').split(',').map((part) => part.trim().split(/\s+/)[0] ?? '')
        )
      ].filter(Boolean)
      for (const reference of references) {
        if (reference.startsWith('//')) violations.push(`${route}: ${reference}`)
        if (/^https?:\/\//i.test(reference) && !reference.startsWith(`${origin}/`)) {
          violations.push(`${route}: ${reference}`)
        }
      }
    }
    expect(violations).toEqual([])
  })

  it('contains no remote CSS request', () => {
    const violations = filesUnder(distDir)
      .filter((path) => path.endsWith('.css'))
      .flatMap((path) => {
        const matches = readFileSync(path, 'utf8').match(/url\(\s*['"]?https?:|@import\s+['"]?https?:/gi)
        return matches ? [`${relative(distDir, path)}: ${matches.join(', ')}`] : []
      })
    expect(violations).toEqual([])
  })
})
